# https://github.com/catalinpit/catalinpit/blob/main/.github/workflows/fetch-blog-articles.yml
# https://raw.githubusercontent.com/catalinpit/catalinpit/refs/heads/main/.github/workflows/fetch-blog-articles.yml

name: Latest blog post workflow
on:
  #schedule: # Run workflow automatically
  #  - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-hashnode-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://alexhedley.com/blog/feed.rss"
